# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.FloatField()),
                ('trigger1', models.BooleanField()),
                ('trigger2', models.BooleanField()),
            ],
        ),
    ]
